export const Gender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER",
};

export const UserRole = {
  PATIENT: "patient",
  DOCTOR: "doctor",
  ADMIN: "admin",
  CLINIC: "clinic",
};
export const DOCTOR_SPECIALTIES = [
  { value: "", label: "All" },
  { value: "anesthesiology", label: "Anesthesiology" },
  { value: "cardiology", label: "Cardiology" },
  { value: "colorectal-surgery", label: "Colorectal Surgery" },
  { value: "dentistry", label: "Dentistry" },
  { value: "dermatology", label: "Dermatology" },
  { value: "ent", label: "ENT (Ear, Nose & Throat)" },
  { value: "endocrinology", label: "Endocrinology" },
  { value: "gastroenterology", label: "Gastroenterology" },
  { value: "general-physician", label: "General Physician" },
  { value: "general-surgery", label: "General Surgery" },
  { value: "gynecologic-oncology", label: "Gynecologic Oncology" },
  { value: "gynecology-obstetrics", label: "Gynecology & Obstetrics" },
  { value: "hematology", label: "Hematology" },
  { value: "hepatology", label: "Hepatology" },
  { value: "medical-oncology", label: "Medical Oncology" },
  { value: "internal-medicine", label: "Internal Medicine" },
  { value: "nephrology", label: "Nephrology" },
  { value: "neurology", label: "Neurology" },
  { value: "neurosurgery", label: "Neurosurgery" },
  { value: "oncology", label: "Oncology" },
  { value: "ophthalmology", label: "Ophthalmology" },
  { value: "orthopedics", label: "Orthopedics" },
  { value: "pediatric-surgery", label: "Pediatric Surgery" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "physical-medicine", label: "Physical Medicine" },
  { value: "plastic-surgery", label: "Plastic Surgery" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "radiation-oncology", label: "Radiation Oncology" },
  { value: "respiratory-medicine", label: "Respiratory Medicine" },
  { value: "rheumatology", label: "Rheumatology" },
  { value: "thoracic-surgery", label: "Thoracic Surgery" },
  { value: "urology", label: "Urology" },
  { value: "vascular-surgery", label: "Vascular Surgery" },
];
export const BANGLADESH_DISTRICTS = [
  { value: "", label: "All" },
  { value: "dhaka", label: "Dhaka" },
  { value: "chittagong", label: "Chittagong" },
  { value: "sylhet", label: "Sylhet" },
  { value: "khulna", label: "Khulna" },
  { value: "barishal", label: "Barishal" },
  { value: "rajshahi", label: "Rajshahi" },
  { value: "rangpur", label: "Rangpur" },
  { value: "mymensingh", label: "Mymensingh" },
  { value: "comilla", label: "Comilla" },
  { value: "feni", label: "Feni" },
  { value: "cox's-bazar", label: "Cox's Bazar" },
  { value: "noakhali", label: "Noakhali" },
  { value: "brahmanbaria", label: "Brahmanbaria" },
  { value: "chandpur", label: "Chandpur" },
  { value: "lakshmipur", label: "Lakshmipur" },
  // Add all 64 districts following the same pattern
];

// Type for strict district value checking
export type BangladeshDistrict = (typeof BANGLADESH_DISTRICTS)[number]["value"];
